### PR TITLE
New Idea - Testing Title

### PR DESCRIPTION
**Pull request by staticmanapp**
Dear human,

Here's a new entry for your approval. :tada:

Merge the pull request to accept it, or close it to send it away.

:heart: Your friend [Staticman](https://staticman.net) :muscle:

---
| Field        | Content                               |
| ------------ | ------------------------------------- |
| status       | Ongoing                               |
| date_posted  | 2017-03-08                            |
| layout       | jobs                                  |
| organization | aalind @ GDG VIT Vellore              |
| org_url      | http://gdgvitvellore.com              |
| title        | Testing Title                         |
| description  | Saple description about your project. |
| tags         | Scraping, Web, Python                 |
| date         | 2017-03-08T12:03:22.622Z              |

### CODE REVIEW

**Comment by aalind0** [comment]
@rultor merge

**Comment by aalind0** [comment]
@rultor merge

**Comment by aalind0** [comment]
@rultor merge

**Comment by aalind0** [comment]
@rultor merge

**Comment by aalind0** [comment]
@rultor deploy

**Comment by ashwini0529** [comment]
@aalind0 check this : https://github.com/yegor256/rultor/issues/1145

**Comment by aalind0** [comment]
@ashwini0529  We have a Rakefile.

**Comment by aalind0** [comment]
Closing as tests completed now. :octocat:

**Pull request closed without merging**
